version: '3.3'
services:

  api:
    image: "mousticrevette/time.api"
    ports:
     - "8080:8080"
    environment:
      - indexDir=/lucene
      - port=8080
      - searchPhrasePageSize=40
    volumes:
      - /var/log/time:/var/log/time
      - /var/lib/time/lucene:/lucene
